name: create-snapshot

on: [push, pull_request]

jobs:
  build-windows:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
        architecture: x64
    - name: Build with Gradle
      run: .\gradlew.bat assemble 
    - name: Create Distribution   
      run: .\.github\workflows\create-distribution-SNAPSHOT-windows-x64.bat "SNAPSHOT-$(([datetime]::now).tostring("yyyy-MM-dd_HH-mm-ss"))"   
    - uses: AButler/upload-release-assets@v2.0
      with:
          files: './.github/workflows/SpaceFX-SNAPSHOT-*-windows-x64.msi'
          release-tag: SNAPSHOT 
          repo-token: ${{ secrets.GITHUB_TOKEN }}   

  build-mac:

    runs-on: [ macos-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
          architecture: x64
      - name: Build with Gradle
        run: .\gradlew.bat assemble
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Create Distribution
        run: ./build_app.sh
      - uses: actions/upload-artifact@v2
        with:
          name: SpaceFX
          path: /build/installer/SpaceFX-1.0.0.dmg
          